### ISSUE TITLE
Improve instructions for regenerating core17_generated.hpp

### ISSUE THREAD

**Issue by akrzemi1** [boostorg/pfr#57]
The instructions on how to regenerate file `include/boost/pfr/detail/core17_generated.hpp` located at https://github.com/boostorg/pfr/blob/develop/misc/generate_cpp17.py#L70 say:

```
`python ./misc/generate_cpp17.py 300 > include/boost/pfr/detail/core17_generated.hpp`
```
The script is written in python2 and when I invoke this command on my default `python` -- which is version 3 -- I get syntax errors (`print` requires parentheses). 

I think you either need to rewrite the script to be python3, or change the instructions to invoke `python2`, or some combination of both of these.

**Comment by apolukhin** [comment]
Thanks for the report!

Now `core17_generated.py` works with Python2 and Python3 + added a smoke test that the script runs without issues
