### ISSUE TITLE
on vs update after... 

### ISSUE THREAD

**Issue by bilbilemm** [boostorg/pfr#59]
struct test{
    int a;
   int b;
};
std::is_constructible<test,int,int>::value; // value is false ... on Latest vs 2019 
so pfr can't work

**Comment by bilbilemm** [comment]
Waiting for Microsoft to fix?

**Comment by apolukhin** [comment]
Hm... what error does it produce?
Mybe there's a workaround for it

**Comment by bilbilemm** [comment]
static_assert(
        is_aggregate_initializable_n<type, result>::value,
        "====================> Boost.PFR: Types with user specified constructors (non-aggregate initializable types) are not supported."
    );
assert --

**Comment by apolukhin** [comment]
They don't define the `__cpp_lib_is_aggregate` macro? That's strange

Could you please compile and run this file https://github.com/boostorg/pfr/blob/develop/test/print_config.cpp and show the output

If you could you please replace the line
https://github.com/boostorg/pfr/blob/e15cb59f76df79d808628ffcdbee15779b357a10/include/boost/pfr/detail/fields_count.hpp#L222
with `#if 1` and show the compile error , that would also help

**Comment by bilbilemm** [comment]
solved thanks

**Comment by apolukhin** [comment]
What was the problem?

**Comment by bilbilemm** [comment]
The version I use is too old
