### ISSUE TITLE
extra semicolon warning

### ISSUE THREAD

**Issue by chybz** [boostorg/pfr#72]
Hi,

GCC 10.2 reports the following warning under `-Wpedantic` (1 of 3 pasted below):

```
boost/pfr/detail/fields_count.hpp:34:6: warning: extra ‘;’ [-Wpedantic]
   34 |     };
      |      ^
```

Thank you for this software masterpiece.

**Comment by apolukhin** [comment]
Thanks for the report!

Please, indicate all the lines with warnings next time
