### ISSUE TITLE
PFR for boost spirit

### ISSUE THREAD

**Issue by denzor200** [boostorg/pfr#74]
Hi, Anton. Recently i created drafted PR with pfr library into fusion. 
https://github.com/boostorg/fusion/pull/232
I invite you to participate in the review, if you wish.

**Comment by apolukhin** [comment]
I've seen it, good job!

I do not maintain the Fusion library and not aware of its internals. My participation won't help :(

BTW, there's a Spirit x3 that does not depend on Fusion, but may also benefit from PFR

**Comment by denzor200** [comment]
Ok. Thanks for the answer!
