### ISSUE TITLE
What's a problem with Visual Studio?

### ISSUE THREAD

**Issue by denzor200** [boostorg/pfr#78]
I tried to compile this example with my VS 2017 (C++14, boost 1.76):
https://github.com/boostorg/pfr/blob/develop/example/get.cpp
And i seen error, like `Boost.PFR requires /std:c++latest or /std:c++17 flags on your compiler.`
Then i just remove the line with this error from config.hpp, and this example works normally.
Is there any reason why pfr is prohibited from working with VS and C++14? Can I make a PR that would remove this error for VS 2017? It would help me in promoting the PFR in fusion.

**Comment by apolukhin** [comment]
Visual Studio may work in C++14 mode... or may not

The rules are quite complex https://github.com/boostorg/pfr/blob/8aa4e0712a0167996c288b52963dbdaddb65b83b/include/boost/pfr/detail/config.hpp#L26-L55 and may not be perfect.

PR are welcome! Do not forget to add C++14 runs to CI here https://github.com/boostorg/pfr/blob/33250407dbb2c4cd9683f5099ca4e2fb8e633821/.github/workflows/ci.yml#L143 and drop this line
