### ISSUE TITLE
Missing "boost/pfr/precise.hpp" (is readme outdated?)

### ISSUE THREAD

**Issue by myxo** [boostorg/pfr#94]
Hi.

README.md has code that
```c++
#include "boost/pfr/precise.hpp"
```
but it missing in repository. It seems that README.md should be updated.

ps. I actually don't know much about pfr, I stumbled on this issue while compiling 3d party library. What header should I replace it with? Just `boost/pfr.hpp`?

**Comment by apolukhin** [comment]
Many thanks for the bug report!

Fixed.
